In [1]:
import yfinance as yf

In [2]:
tickers = yf.Tickers('AAPL GOOGL MSFT AMZN META')
df = yf.download(['MSFT', 'AAPL', 'GOOG'], period='1mo')

[*********************100%***********************]  3 of 3 completed

In [3]:
print(type(df))

<class 'pandas.DataFrame'>

In [4]:
from sqlalchemy import create_engine
import psycopg2

In [5]:
db_url="postgresql+psycopg2://my_user:password_132@localhost:5732/stocks_db"

In [6]:
engine = create_engine(db_url)

In [7]:
df = df['Close'].reset_index()

df.rename(columns={'index': 'date'}, inplace=True)

df_long = df.melt(
    id_vars='date',
    var_name='ticker',
    value_name='close_price'
)

print(df_long.head())

        date ticker  close_price
0 2026-04-28   AAPL   270.460815
1 2026-04-29   AAPL   269.921326
2 2026-04-30   AAPL   271.100250
3 2026-05-01   AAPL   279.882141
4 2026-05-04   AAPL   276.575165

In [8]:
df = df_long
df.head(15)

         date ticker  close_price
0  2026-04-28   AAPL   270.460815
1  2026-04-29   AAPL   269.921326
2  2026-04-30   AAPL   271.100250
3  2026-05-01   AAPL   279.882141
4  2026-05-04   AAPL   276.575165
5  2026-05-05   AAPL   283.918427
6  2026-05-06   AAPL   287.245361
7  2026-05-07   AAPL   287.175415
8  2026-05-08   AAPL   293.050018
9  2026-05-11   AAPL   292.679993
10 2026-05-12   AAPL   294.799988
11 2026-05-13   AAPL   298.869995
12 2026-05-14   AAPL   298.209991
13 2026-05-15   AAPL   300.230011
14 2026-05-18   AAPL   297.839996

In [9]:
df

         date ticker  close_price
0  2026-04-28   AAPL   270.460815
1  2026-04-29   AAPL   269.921326
2  2026-04-30   AAPL   271.100250
3  2026-05-01   AAPL   279.882141
4  2026-05-04   AAPL   276.575165
..        ...    ...          ...
58 2026-05-20   MSFT   420.149994
59 2026-05-21   MSFT   419.089996
60 2026-05-22   MSFT   418.570007
61 2026-05-26   MSFT   416.029999
62 2026-05-27   MSFT   412.670013

[63 rows x 3 columns]

In [10]:
df.to_sql('raw_stocks', engine, if_exists='replace', index=False)

63

In [11]:
import requests

In [12]:
exchange_rate_api_url="https://open.er-api.com/v6/latest/USD"
res = requests.get(exchange_rate_api_url)
response = res.json()
print(response)

{'result': 'success', 'provider': 'https://www.exchangerate-api.com', 'documentation': 'https://www.exchangerate-api.com/docs/free', 'terms_of_use': 'https://www.exchangerate-api.com/terms', 'time_last_update_unix': 1779926551, 'time_last_update_utc': 'Thu, 28 May 2026 00:02:31 +0000', 'time_next_update_unix': 1780014061, 'time_next_update_utc': 'Fri, 29 May 2026 00:21:01 +0000', 'time_eol_unix': 0, 'base_code': 'USD', 'rates': {'USD': 1, 'AED': 3.6725, 'AFN': 63.268208, 'ALL': 81.918986, 'AMD': 367.872364, 'ANG': 1.79, 'AOA': 927.032151, 'ARS': 1411.1796, 'AUD': 1.400848, 'AWG': 1.79, 'AZN': 1.69968, 'BAM': 1.68152, 'BBD': 2, 'BDT': 122.719189, 'BGN': 1.68152, 'BHD': 0.376, 'BIF': 2976.052129, 'BMD': 1, 'BND': 1.277352, 'BOB': 6.921684, 'BRL': 5.047732, 'BSD': 1, 'BTN': 95.807788, 'BWP': 13.622997, 'BYN': 2.743995, 'BZD': 2, 'CAD': 1.383083, 'CDF': 2264.963045, 'CHF': 0.787015, 'CLF': 0.022634, 'CLP': 894.659507, 'CNH': 6.778968, 'CNY': 6.793906, 'COP': 3670.042314, 'CRC': 452.627554, 'CUP': 24, 'CVE': 94.800069, 'CZK': 20.874965, 'DJF': 177.721, 'DKK': 6.415696, 'DOP': 58.953457, 'DZD': 132.911143, 'EGP': 52.224102, 'ERN': 15, 'ETB': 157.996659, 'EUR': 0.859749, 'FJD': 2.202287, 'FKP': 0.744561, 'FOK': 6.415118, 'GBP': 0.744561, 'GEL': 2.667496, 'GGP': 0.744561, 'GHS': 11.671111, 'GIP': 0.744561, 'GMD': 74.141816, 'GNF': 8753.841646, 'GTQ': 7.624227, 'GYD': 208.993719, 'HKD': 7.834766, 'HNL': 26.599923, 'HRK': 6.477768, 'HTG': 130.821737, 'HUF': 305.099387, 'IDR': 17814.213382, 'ILS': 2.831936, 'IMP': 0.744561, 'INR': 95.808304, 'IQD': 1308.818232, 'IRR': 1304007.301044, 'ISK': 123.077112, 'JEP': 0.744561, 'JMD': 157.362713, 'JOD': 0.709, 'JPY': 159.471405, 'KES': 129.487688, 'KGS': 87.479796, 'KHR': 4017.2635, 'KID': 1.400846, 'KMF': 422.96809, 'KRW': 1500.684943, 'KWD': 0.308853, 'KYD': 0.833333, 'KZT': 479.816438, 'LAK': 21910.460464, 'LBP': 89500, 'LKR': 327.274307, 'LRD': 182.544306, 'LSL': 16.363729, 'LYD': 6.348166, 'MAD': 9.179169, 'MDL': 17.306023, 'MGA': 4199.326674, 'MKD': 52.951482, 'MMK': 2099.313151, 'MNT': 3575.373324, 'MOP': 8.069809, 'MRU': 39.939379, 'MUR': 47.272235, 'MVR': 15.445751, 'MWK': 1739.602299, 'MXN': 17.359847, 'MYR': 3.965034, 'MZN': 63.791571, 'NAD': 16.363729, 'NGN': 1372.421059, 'NIO': 36.75836, 'NOK': 9.27736, 'NPR': 153.292461, 'NZD': 1.696874, 'OMR': 0.384497, 'PAB': 1, 'PEN': 3.408738, 'PGK': 4.364382, 'PHP': 61.433698, 'PKR': 278.523885, 'PLN': 3.640492, 'PYG': 6131.922851, 'QAR': 3.64, 'RON': 4.504208, 'RSD': 100.889831, 'RUB': 71.005943, 'RWF': 1467.530004, 'SAR': 3.75, 'SBD': 7.933206, 'SCR': 13.999007, 'SDG': 585.789612, 'SEK': 9.291267, 'SGD': 1.277352, 'SHP': 0.744561, 'SLE': 24.581085, 'SLL': 24581.085213, 'SOS': 570.95352, 'SRD': 37.14565, 'SSP': 4767.525025, 'STN': 21.063816, 'SYP': 113.040386, 'SZL': 16.363729, 'THB': 32.611244, 'TJS': 9.232308, 'TMT': 3.498493, 'TND': 2.895903, 'TOP': 2.361821, 'TRY': 45.896091, 'TTD': 6.778607, 'TVD': 1.400846, 'TWD': 31.430857, 'TZS': 2602.251186, 'UAH': 44.28947, 'UGX': 3760.513745, 'UYU': 39.986759, 'UZS': 11998.91948, 'VES': 544.5794, 'VND': 26321.729199, 'VUV': 118.435635, 'WST': 2.680346, 'XAF': 563.957454, 'XCD': 2.7, 'XCG': 1.79, 'XDR': 0.730045, 'XOF': 563.957454, 'XPF': 102.5954, 'YER': 238.559827, 'ZAR': 16.363734, 'ZMW': 18.672097, 'ZWG': 26.4647, 'ZWL': 26.4647}}

In [13]:
import pandas as pd

In [14]:
rates_df = pd.DataFrame({
    'currency': response['rates'].keys(),
    'value': response['rates'].values()
})

In [15]:
rates_df.head()

  currency       value
0      USD    1.000000
1      AED    3.672500
2      AFN   63.268208
3      ALL   81.918986
4      AMD  367.872364

In [16]:
rates_df.to_sql('raw_fx_rates', engine, if_exists='replace', index=False)

166